FROM python:3.12-slim

# Instale pacotes necessários para acessar o MS-SQLServer
RUN apt-get update && \
    apt-get install --no-install-recommends -y unixodbc unixodbc-dev curl gnupg2 && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install --no-install-recommends -y msodbcsql17 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

COPY requirements.txt Pipfile Pipfile.lock ./
RUN pip install --no-cache-dir pipenv && \
    pipenv install --system --deploy --ignore-pipfile

COPY . .

EXPOSE 2003
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "2001"]