SELECT TOP (1000) [id]
      ,[id_elasticsearch]
      ,[payload]
      ,[status]
      ,[data_criacao]
      ,[data_inicio_processamento]
      ,[data_fim_processamento]
      ,[erro_mensagem]
      ,[tentativas]
      ,[id_agente]
      ,[worker]
  FROM [IA].[dbo].[fila_processamento_agentes]