SELECT TOP (1000) [id]
      ,[data]
      ,[prompt_original]
      ,[prompt_final]
      ,[resposta]
      ,[prompt_tokens]
      ,[completion_tokens]
      ,[total_tokens]
      ,[user_gampes]
      ,[idfuncao]
      ,[idorgao]
      ,[modelo]
      ,[tempo_processamento]
  FROM [IA].[dbo].[rag_gampes]